/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as AddressesAddressRouteImport } from './routes/addresses.$address'
import { Route as BlocksBlockRouteImport } from './routes/blocks.$block'
import { Route as TransactionsTransactionRouteImport } from './routes/transactions.$transaction'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesAddressRoute = AddressesAddressRouteImport.update({
  id: '/$address',
  path: '/$address',
  getParentRoute: () => AddressesRoute,
} as any)
const BlocksBlockRoute = BlocksBlockRouteImport.update({
  id: '/$block',
  path: '/$block',
  getParentRoute: () => BlocksRoute,
} as any)
const TransactionsTransactionRoute = TransactionsTransactionRouteImport.update({
  id: '/$transaction',
  path: '/$transaction',
  getParentRoute: () => TransactionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRouteWithChildren
  '/blocks': typeof BlocksRouteWithChildren
  '/overview': typeof OverviewRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/addresses/$address': typeof AddressesAddressRoute
  '/blocks/$block': typeof BlocksBlockRoute
  '/transactions/$transaction': typeof TransactionsTransactionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRouteWithChildren
  '/blocks': typeof BlocksRouteWithChildren
  '/overview': typeof OverviewRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/addresses/$address': typeof AddressesAddressRoute
  '/blocks/$block': typeof BlocksBlockRoute
  '/transactions/$transaction': typeof TransactionsTransactionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRouteWithChildren
  '/blocks': typeof BlocksRouteWithChildren
  '/overview': typeof OverviewRoute
  '/transactions': typeof TransactionsRouteWithChildren
  '/addresses/$address': typeof AddressesAddressRoute
  '/blocks/$block': typeof BlocksBlockRoute
  '/transactions/$transaction': typeof TransactionsTransactionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/blocks'
    | '/overview'
    | '/transactions'
    | '/addresses/$address'
    | '/blocks/$block'
    | '/transactions/$transaction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/blocks'
    | '/overview'
    | '/transactions'
    | '/addresses/$address'
    | '/blocks/$block'
    | '/transactions/$transaction'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/blocks'
    | '/overview'
    | '/transactions'
    | '/addresses/$address'
    | '/blocks/$block'
    | '/transactions/$transaction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRouteWithChildren
  BlocksRoute: typeof BlocksRouteWithChildren
  OverviewRoute: typeof OverviewRoute
  TransactionsRoute: typeof TransactionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses/$address': {
      id: '/addresses/$address'
      path: '/$address'
      fullPath: '/addresses/$address'
      preLoaderRoute: typeof AddressesAddressRouteImport
      parentRoute: typeof AddressesRoute
    }
    '/blocks/$block': {
      id: '/blocks/$block'
      path: '/$block'
      fullPath: '/blocks/$block'
      preLoaderRoute: typeof BlocksBlockRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/transactions/$transaction': {
      id: '/transactions/$transaction'
      path: '/$transaction'
      fullPath: '/transactions/$transaction'
      preLoaderRoute: typeof TransactionsTransactionRouteImport
      parentRoute: typeof TransactionsRoute
    }
  }
}

interface AddressesRouteChildren {
  AddressesAddressRoute: typeof AddressesAddressRoute
}

const AddressesRouteChildren: AddressesRouteChildren = {
  AddressesAddressRoute: AddressesAddressRoute,
}

const AddressesRouteWithChildren = AddressesRoute._addFileChildren(
  AddressesRouteChildren,
)

interface BlocksRouteChildren {
  BlocksBlockRoute: typeof BlocksBlockRoute
}

const BlocksRouteChildren: BlocksRouteChildren = {
  BlocksBlockRoute: BlocksBlockRoute,
}

const BlocksRouteWithChildren =
  BlocksRoute._addFileChildren(BlocksRouteChildren)

interface TransactionsRouteChildren {
  TransactionsTransactionRoute: typeof TransactionsTransactionRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsTransactionRoute: TransactionsTransactionRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRouteWithChildren,
  BlocksRoute: BlocksRouteWithChildren,
  OverviewRoute: OverviewRoute,
  TransactionsRoute: TransactionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
